services:
  - type: web
    name: yatrazen-backend
    env: java
    region: oregon
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: JAVA_OPTS
        value: "-Xmx512m"
